name: Full Stack CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies (Frontend)
        run: cd frontend && npm install
        
      - name: Build frontend
        run: cd frontend && npm run build
      
      - name: Install dependencies (Backend)
        run: cd backend && npm install
        
      - name: Run backend tests
        run: cd backend && npm test

      - name: Deploy to production
      - run: npm run deploy
